POST /api/v1/savedetails
Content-Type: application/json

{
  "period": 4,
  "num_users": 5
}

###
POST http://localhost:8090/login
Content-Type: application/json

{
  "username": "ninja",
  "password": "ninjalah"
}

###

###
